// packages/angular/projects/ds-rte-lib/src/lib/components/tag/tag.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, computed } from "@angular/core";
import { TagProps } from "@rte-ds/core/components/tag/tag.interface";

import { isValidIconName } from "../icon/icon-map";
import { IconComponent } from "../icon/icon.component";
import { RegularIconIdKey, TogglableIconIdKey } from "../icon/icon.service";

@Component({
  selector: "rte-tag",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./tag.component.html",
  styleUrl: "./tag.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TagComponent {
  readonly tagType = input<TagProps["tagType"]>("status");
  readonly status = input<TagProps["status"]>("success");
  readonly color = input<TagProps["color"]>("brand");
  readonly compactSpacing = input<boolean>(false);
  readonly label = input<string>("");
  readonly showLeftIcon = input<boolean>(false);
  readonly iconName = input<RegularIconIdKey | TogglableIconIdKey>();

  readonly computedIconName = computed(() => {
    if (this.tagType() === "status") {
      const statusIconMap: Record<string, RegularIconIdKey | TogglableIconIdKey> = {
        success: "check-circle",
        information: "info",
        warning: "warning",
        alert: "dangerous",
      };
      const statusValue = this.status();
      if (statusValue && statusIconMap[statusValue]) {
        return statusIconMap[statusValue];
      }
    }
    return this.iconName() ?? "check";
  });

  readonly isValidIconName = computed(() => {
    const iconName = this.computedIconName();
    return !!iconName && isValidIconName(iconName);
  });
}

// packages/react/src/components/tag/Tag.tsx
import { TagProps as TagPropsCore } from "@rte-ds/core/components/tag/tag.interface";
import { forwardRef } from "react";

import Icon, { RegularIconIdKey, TogglableIconIdKey } from "../icon/Icon";
import { isValidIconName } from "../icon/IconMap";

import style from "./Tag.module.scss";

interface TagProps extends Omit<TagPropsCore, "iconName">, Omit<React.HTMLAttributes<HTMLDivElement>, "color"> {
  iconName?: RegularIconIdKey | TogglableIconIdKey;
}

const statusIconMap: Record<string, RegularIconIdKey | TogglableIconIdKey> = {
  success: "check-circle",
  information: "info",
  warning: "warning",
  alert: "dangerous",
};

const Tag = forwardRef<HTMLDivElement, TagProps>(
  ({ tagType = "status", status, color, compactSpacing, label, showLeftIcon = false, iconName, ...props }, ref) => {
    if (tagType === "status" && status && statusIconMap[status]) {
      iconName = statusIconMap[status];
    }

    if (iconName && !isValidIconName(iconName)) {
      console.warn(`Tag: Invalid icon name "${iconName}". Please use a valid icon key.`);
      return null;
    }

    return (
      <div
        ref={ref}
        className={style["tag"]}
        data-tag-type={tagType}
        data-status={status}
        data-color={color}
        data-compact-spacing={compactSpacing}
        {...props}
      >
        {iconName && isValidIconName(iconName) && (tagType === "status" || showLeftIcon) && (
          <Icon name={iconName} size={16} />
        )}
        {label && (
          <label className={style["tag-label"]} data-compact-spacing={compactSpacing}>
            {label}
          </label>
        )}
      </div>
    );
  },
);

export default Tag;
