// packages/react/src/components/sideNav/SideNav.tsx
import { NavItemProps } from "@rte-ds/core/components/side-nav/nav-item/nav-item.interface";
import { dividerAppearanceBySideNavAppearance } from "@rte-ds/core/components/side-nav/side-nav.constants";
import { SideNavProps as CoreSideNavProps } from "@rte-ds/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";
import { forwardRef, Fragment, ReactNode, useEffect, useState } from "react";

import { useActiveKeyboard } from "../../hooks/useActiveKeyboard";
import Divider from "../divider/Divider";

import BaseSideNav from "./baseSideNav/BaseSideNav";
import NavItem from "./navItem/NavItem";
import NavMenu from "./navMenu/NavMenu";
import style from "./SideNav.module.scss";

interface SideNavProps extends Partial<CoreSideNavProps>, Omit<React.HTMLAttributes<HTMLDivElement>, "content"> {
  children?: ReactNode;
  defaultCollapsed?: boolean;
  onCollapsedChange?: (collapsed: boolean) => void;
}

const TRANSITION_DURATION = 300;

const SideNav = forwardRef<HTMLElement | HTMLDivElement, SideNavProps>(
  (
    {
      size = "m",
      collapsible,
      children,
      headerConfig,
      items,
      footerItems,
      collapsed,
      defaultCollapsed = false,
      onCollapsedChange,
      appearance = "brand",
      activeItem,
    }: SideNavProps,
    ref,
  ) => {
    const [isCollapsed, setIsCollapsed] = useState(collapsed ?? defaultCollapsed);
    const [shouldShowTitle, setShouldShowTitle] = useState(true);

    useEffect(() => {
      if (collapsed !== undefined) {
        setIsCollapsed(collapsed);
      }
    }, [collapsed]);

    useEffect(() => {
      if (isCollapsed) {
        setShouldShowTitle(false);
      } else {
        const timer = setTimeout(() => {
          setShouldShowTitle(true);
        }, TRANSITION_DURATION);
        return () => clearTimeout(timer);
      }
    }, [isCollapsed]);

    const collapseSideNav = () => {
      const newCollapsed = !isCollapsed;
      if (collapsed === undefined) {
        setIsCollapsed(newCollapsed);
      }
      onCollapsedChange?.(newCollapsed);
    };

    const collapseIcon = isCollapsed ? "arrow-double-right" : "arrow-double-left";

    const dividerAppearance = dividerAppearanceBySideNavAppearance[appearance];

    const handleHeaderKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      if ([SPACE_KEY, ENTER_KEY].includes(e.key)) {
        e.preventDefault();
        if (headerConfig?.onClick) {
          headerConfig.onClick();
        }
      }
    };

    const { onKeyDown: headerOnKeyDown } = useActiveKeyboard<HTMLDivElement>(
      { onKeyDown: handleHeaderKeyDown },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY],
      },
    );

    const headerTitleContent = (
      <div className={style.sideNavHeaderTitle}>
        <div className={style.sideNavHeaderIdentifier}>{headerConfig?.identifier}</div>
        {isCollapsed ? "" : <h1 data-hidden={!shouldShowTitle}>{headerConfig?.title}</h1>}
      </div>
    );

    const ariaLabel = headerConfig?.ariaLabel;

    const headerTitleLink = (
      <a
        href={headerConfig?.link ?? ""}
        className={style.sideNavHeaderTitleContainer}
        onClick={headerConfig?.onClick}
        aria-label={ariaLabel}
      >
        {headerTitleContent}
      </a>
    );

    const clickableHeaderTitle = (
      <div
        className={style.sideNavHeaderTitleContainer}
        tabIndex={0}
        onClick={headerConfig?.onClick}
        onKeyDown={headerOnKeyDown}
        role="button"
        aria-label={ariaLabel}
      >
        {headerTitleContent}
      </div>
    );

    const headerTitle = headerConfig?.link ? (
      headerTitleLink
    ) : headerConfig?.onClick ? (
      clickableHeaderTitle
    ) : (
      <div className={style.sideNavHeaderTitleContainer}>{headerTitleContent}</div>
    );

    function renderNavItems(itemsToRender: NavItemProps[] | undefined) {
      if (!itemsToRender?.length) {
        return null;
      }

      return (
        <ul>
          {itemsToRender.map((item: NavItemProps) => {
            const hasNestedItems = item.items?.length;
            if (hasNestedItems) {
              return (
                <NavMenu
                  key={item.id}
                  badge={item.badge}
                  label={item.label}
                  icon={item.icon}
                  showIcon={item.showIcon}
                  collapsed={isCollapsed}
                  link={item.link}
                  onClick={item.onClick}
                  items={item.items || []}
                  appearance={appearance}
                  showDivider={item.showDivider}
                />
              );
            }
            return (
              <Fragment key={item.id}>
                <li>
                  <NavItem
                    id={item.id}
                    badge={item.badge}
                    label={item.label}
                    icon={item.icon}
                    showIcon={item.showIcon}
                    collapsed={isCollapsed}
                    link={item.link}
                    onClick={item.onClick}
                    appearance={appearance}
                    active={item.id === activeItem && !!activeItem}
                  />
                </li>
                {item.showDivider && <Divider appearance={dividerAppearance} />}
              </Fragment>
            );
          })}
        </ul>
      );
    }

    return (
      <BaseSideNav
        ref={ref}
        size={size}
        collapsed={isCollapsed}
        appearance={appearance}
        style={{ height: "100vh" }}
        header={
          <div className={style.sideNavHeaderContainer}>
            <div className={style.sideNavHeader} data-collapsed={isCollapsed} data-appearance={appearance}>
              {headerTitle}
              <div className={style.sideNavHeaderVersion} data-hidden={!shouldShowTitle}>
                <span>{headerConfig?.version}</span>
              </div>
            </div>
            <Divider appearance={dividerAppearance} />
          </div>
        }
        body={<div className={style.sideNavBody}>{renderNavItems(items)}</div>}
        footer={
          (footerItems?.length || collapsible) && (
            <div className={style.sideNavFooterContainer}>
              {footerItems?.length && <div className={style.sideNavFooterItems}>{renderNavItems(footerItems)}</div>}
              <Divider appearance={dividerAppearance} />
              <div className={style.sideNavFooter}>
                {collapsible && (
                  <div className={style.collapsibleSection}>
                    <NavItem
                      id="collapse-button"
                      icon={collapseIcon}
                      showIcon={true}
                      collapsed={isCollapsed}
                      onClick={collapseSideNav}
                      label={isCollapsed ? "Ouvrir le menu" : "Réduire le menu"}
                      appearance={appearance}
                      role="button"
                    />
                  </div>
                )}
              </div>
            </div>
          )
        }
      >
        {children}
      </BaseSideNav>
    );
  },
);

export default SideNav;

// packages/angular/projects/ds-rte-lib/src/lib/components/side-nav/side-nav.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, input, output, signal } from "@angular/core";
import { DividerAppearance } from "@rte-ds/core/components/divider/divider.interface";
import { NavItemProps } from "@rte-ds/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps } from "@rte-ds/core/components/side-nav/nav-menu/nav-menu.interface";
import { dividerAppearanceBySideNavAppearance } from "@rte-ds/core/components/side-nav/side-nav.constants";
import { SideNavAppearance, SideNavHeaderConfig } from "@rte-ds/core/components/side-nav/side-nav.interface";
import { SideNavSize } from "@rte-ds/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";

import { DividerComponent } from "../divider/divider.component";

import { BaseSideNavComponent } from "./base-side-nav/base-side-nav.component";
import { NavItemComponent } from "./nav-item/nav-item.component";
import { NavMenuComponent, NavMenuOpenChangeEvent } from "./nav-menu/nav-menu.component";

const TRANSITION_DURATION = 300;

@Component({
  selector: "rte-side-nav",
  imports: [CommonModule, BaseSideNavComponent, DividerComponent, NavItemComponent, NavMenuComponent],
  standalone: true,
  templateUrl: "./side-nav.component.html",
  styleUrl: "./side-nav.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SideNavComponent {
  readonly size = input<SideNavSize>("m" as SideNavSize);
  readonly collapsible = input<boolean>(false);
  readonly headerConfig = input<SideNavHeaderConfig | undefined>();
  readonly items = input<NavItemProps[]>([]);
  readonly footerItems = input<NavItemProps[] | undefined>();
  readonly collapsed = input<boolean>(false);
  readonly appearance = input<SideNavAppearance>("brand");

  readonly isCollapsed = signal<boolean>(false);
  readonly shouldShowTitle = signal<boolean>(true);

  readonly itemClicked = output<string>();

  private titleTimeoutId: ReturnType<typeof setTimeout> | null = null;

  constructor() {
    effect(
      () => {
        this.isCollapsed.set(this.collapsed());
      },
      { allowSignalWrites: true },
    );

    effect(
      () => {
        if (this.titleTimeoutId) {
          clearTimeout(this.titleTimeoutId);
          this.titleTimeoutId = null;
        }

        if (this.isCollapsed()) {
          this.shouldShowTitle.set(false);
        } else {
          this.titleTimeoutId = setTimeout(() => {
            this.shouldShowTitle.set(true);
            this.titleTimeoutId = null;
          }, TRANSITION_DURATION);
        }
      },
      { allowSignalWrites: true },
    );
  }

  readonly collapseIcon = computed<string>(() => {
    return this.isCollapsed() ? "arrow-double-right" : "arrow-double-left";
  });

  readonly dividerAppearance = computed<DividerAppearance>(() => {
    return dividerAppearanceBySideNavAppearance[this.appearance()];
  });

  handleHeaderKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      const config = this.headerConfig();
      if (config?.onClick) {
        config.onClick();
      }
    }
  }

  handleHeaderClick(): void {
    const config = this.headerConfig();
    if (config?.onClick) {
      config.onClick();
    }
  }

  hasNestedItems(item: NavItemProps): item is NavMenuProps {
    return !!item.items?.length;
  }

  handleItemClick(itemId: string): void {
    this.itemClicked.emit(itemId);
  }

  handleFooterItemClick(itemId: string): void {
    this.itemClicked.emit(itemId);
  }

  handleMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const targetMenu = this.items().find((item) => item.id === event.id);
    if (targetMenu) {
      (targetMenu as NavMenuProps).open = event.open;
    }
  }

  handleFooterMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const targetMenu = this.footerItems()?.find((item) => item.id === event.id);
    if (targetMenu) {
      (targetMenu as NavMenuProps).open = event.open;
    }
  }

  handleCollapseClick(): void {
    this.isCollapsed.set(!this.isCollapsed());
  }
}
