// packages/angular/projects/ds-rte-lib/src/lib/components/switch/switch.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, signal, OnInit, output } from "@angular/core";
import { switchHeight, switchWidth } from "@rte-ds/core/components/switch/switch.constants";
import { SwitchProps } from "@rte-ds/core/components/switch/switch.interface";

import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-switch",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./switch.component.html",
  styleUrl: "./switch.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchComponent implements OnInit {
  readonly label = input("");
  readonly appearance = input<SwitchProps["appearance"]>("brand");
  readonly showLabel = input(true);
  readonly showIcon = input(true);
  readonly disabled = input(false);
  readonly readOnly = input(false);
  readonly checked = input(false);

  readonly stateChange = output<Event>();

  switchHeight = switchHeight;
  switchWidth = switchWidth;

  readonly isChecked = signal(false);

  ngOnInit() {
    this.isChecked.set(this.checked());
  }

  handleChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.isChecked.set(target.checked);
    this.stateChange.emit(event);
  }

  handleClick(event: MouseEvent): void {
    if (this.readOnly() || this.disabled()) {
      event.stopPropagation();
    } else {
      const inputElement = (event.currentTarget as HTMLInputElement).querySelector<HTMLInputElement>(
        'input[type="checkbox"]',
      );
      if (inputElement) {
        inputElement.checked = !this.isChecked();
        const changeEvent = new Event("change", { bubbles: true });
        Object.defineProperty(changeEvent, "target", {
          value: inputElement,
          writable: false,
        });
        this.handleChange(changeEvent);
      }
    }
  }
}

// packages/react/src/components/switch/Switch.tsx
import { switchHeight, switchWidth } from "@rte-ds/core/components/switch/switch.constants";
import { SwitchProps as CoreSwitchProps } from "@rte-ds/core/components/switch/switch.interface";
import { InputHTMLAttributes, useState } from "react";

import Icon from "../icon/Icon";
import { concatClassNames } from "../utils";

import style from "./Switch.module.scss";

interface SwitchProps extends CoreSwitchProps, InputHTMLAttributes<HTMLInputElement> {
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
}

const Switch = ({
  label,
  appearance = "brand",
  showLabel = true,
  showIcon = true,
  disabled = false,
  readOnly = false,
  checked = false,
  onChange,
  ...props
}: SwitchProps) => {
  const [isChecked, setIsChecked] = useState(checked);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsChecked(e.target.checked);
    onChange?.(e);
  };

  const handleClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (readOnly || disabled) {
      e.stopPropagation();
    } else {
      const inputElement = e.currentTarget.querySelector('input[type="checkbox"]') as HTMLInputElement;
      if (inputElement) {
        inputElement.checked = !isChecked;
        const syntheticEvent = {
          target: inputElement,
          currentTarget: inputElement,
        } as React.ChangeEvent<HTMLInputElement>;
        handleChange(syntheticEvent);
      }
    }
  };

  return (
    <div
      className={style["switch-container"]}
      data-appearance={appearance}
      data-disabled={disabled}
      data-read-only={readOnly}
      data-checked={isChecked}
      onClick={handleClick}
    >
      <input
        aria-label={label}
        type="checkbox"
        role="switch"
        name={label}
        className={style["switch"]}
        disabled={disabled}
        defaultChecked={isChecked}
        readOnly={readOnly}
        style={{
          minHeight: switchHeight,
          minWidth: switchWidth,
        }}
        {...props}
      />
      <div className={style["switch-icon-check"]} data-checked={isChecked}>
        {showIcon && isChecked && <Icon name="check" size={16} />}
        {showIcon && !isChecked && <Icon name="close" size={16} />}
      </div>
      {showLabel && label && (
        <label htmlFor={label} className={concatClassNames(style["switch-label"])}>
          {label}
        </label>
      )}
    </div>
  );
};

export default Switch;
