// packages/angular/projects/ds-rte-lib/src/lib/components/assistive-text/assistive-text.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, ChangeDetectionStrategy } from "@angular/core";
import { ASSISTIVE_TEXT_ICON_SIZE } from "@rte-ds/core/components/assistive-text/assistive-text.constants";
import { AssistiveTextProps } from "@rte-ds/core/components/assistive-text/assistive-text.interface";
import { getIconNameFromAppearance } from "@rte-ds/core/components/assistive-text/assistive-text.utils";

import { IconComponent } from "../icon/icon.component";
import { LinkComponent } from "../link/link.component";

@Component({
  selector: "rte-assistive-text",
  imports: [CommonModule, IconComponent, LinkComponent],
  standalone: true,
  templateUrl: "./assistive-text.component.html",
  styleUrl: "./assistive-text.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AssistiveTextComponent {
  readonly label = input<string>();
  readonly appearance = input<AssistiveTextProps["appearance"]>("description");
  readonly showIcon = input<boolean>(false);
  readonly href = input<string>();
  readonly width = input<number>();

  readonly isLink = computed(() => {
    return this.appearance() === "link" && this.href() !== undefined;
  });

  readonly widthStyle = computed(() => {
    return `${this.width()}px`;
  });

  readonly assistiveTextIconSize = ASSISTIVE_TEXT_ICON_SIZE;

  readonly iconName = computed(() => {
    return getIconNameFromAppearance(this.appearance()!);
  });
}

// packages/react/src/components/assistivetext/AssistiveText.tsx
import { ASSISTIVE_TEXT_ICON_SIZE } from "@rte-ds/core/components/assistive-text/assistive-text.constants";
import { AssistiveTextProps } from "@rte-ds/core/components/assistive-text/assistive-text.interface";
import { getIconNameFromAppearance } from "@rte-ds/core/components/assistive-text/assistive-text.utils";

import Icon from "../icon/Icon";
import Link from "../link/Link";

import styles from "./AssistiveText.module.scss";

const AssistiveText = ({ label, appearance, showIcon, href, width }: AssistiveTextProps) => {
  const icon = getIconNameFromAppearance(appearance);

  return (
    <div className={styles["assistive-text"]} data-appearance={appearance} style={{ width: `${width}px` }}>
      {showIcon && icon && (
        <Icon
          name={icon}
          appearance="outlined"
          className={styles[`assistive-icon-${appearance}`]}
          size={ASSISTIVE_TEXT_ICON_SIZE}
        />
      )}
      {appearance === "link" ? <Link label={label} href={href} externalLink /> : <span>{label}</span>}
    </div>
  );
};

export default AssistiveText;
