// packages/angular/projects/ds-rte-lib/src/lib/components/card/card.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input, output } from "@angular/core";
import { cardSize } from "@rte-ds/core/components/card/card.constats";
import { CardType } from "@rte-ds/core/components/card/card.interface";
import { Size } from "@rte-ds/core/components/common/common-types";
import { ENTER_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";

@Component({
  selector: "rte-card",
  imports: [CommonModule],
  standalone: true,
  templateUrl: "./card.component.html",
  styleUrl: "./card.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardComponent {
  readonly size = input<Size>("m");
  readonly cardType = input<CardType>("default");
  readonly clickable = input<boolean>(false);
  readonly disabled = input<boolean>(false);

  readonly ariaLabel = input<string | undefined>(undefined);
  readonly ariaLabelledby = input<string | undefined>(undefined);
  readonly ariaRole = input<string | undefined>(undefined);

  readonly cardClicked = output<void>();

  readonly cardWidth = computed(() => `${cardSize[this.size()]}px`);

  readonly tabIndex = computed(() => (this.clickable() ? 0 : -1));

  onClick(): void {
    if (!this.disabled() && this.clickable()) {
      this.cardClicked.emit();
    }
  }

  onKeyDown(event: KeyboardEvent): void {
    if (!this.disabled() && this.clickable()) {
      if ([ENTER_KEY, SPACE_KEY].includes(event.key)) {
        event.preventDefault();
        this.cardClicked.emit();
      }
    }
  }
}

// packages/react/src/components/card/Card.tsx
import { cardSize } from "@rte-ds/core/components/card/card.constats";
import { CardProps as CardPropsCore } from "@rte-ds/core/components/card/card.interface";
import { ENTER_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";
import { HTMLAttributes, forwardRef, KeyboardEvent } from "react";

import { useActiveKeyboard } from "../../hooks/useActiveKeyboard";

import styles from "./Card.module.scss";

interface CardProps extends CardPropsCore, Omit<HTMLAttributes<HTMLDivElement>, "onClick"> {
  onClick?: () => void;
}

const Card = forwardRef<HTMLDivElement, CardProps>(
  (
    { size = "m", cardType = "default", clickable = false, disabled = false, children, onClick, style, ...props },
    ref,
  ) => {
    const keyboardHandler = (event: KeyboardEvent<HTMLDivElement>) => {
      if (!disabled && clickable && (event.key === SPACE_KEY || event.key === ENTER_KEY)) {
        event.preventDefault();
        onClick?.();
      }
    };

    const handleOnClick = () => {
      if (!disabled && clickable) {
        onClick?.();
      }
    };

    const { onKeyDown, onKeyUp, onBlur } = useActiveKeyboard<HTMLDivElement>(
      { onKeyUp: keyboardHandler },
      {
        interactiveKeyCodes: [SPACE_KEY, ENTER_KEY],
      },
    );

    return (
      <div
        ref={ref}
        className={styles.card}
        style={{ width: cardSize[size], ...style }}
        data-card-type={cardType}
        data-clickable={clickable}
        data-disabled={disabled}
        tabIndex={clickable ? 0 : -1}
        onClick={handleOnClick}
        onKeyDown={onKeyDown}
        onKeyUp={onKeyUp}
        onBlur={onBlur}
        {...props}
      >
        {children}
      </div>
    );
  },
);

export default Card;
