// packages/react/src/components/splitButton/SplitButton.tsx
import { ARROW_DOWN_KEY, ENTER_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";
import { ButtonHTMLAttributes, ForwardedRef, forwardRef, KeyboardEvent, MouseEvent, useRef, useState } from "react";

import { shouldDisplayBadge } from "../../core-types/badge/badge.utils";
import { DropdownProps } from "../../core-types/dropdown/dropdown.interface";
import {
  splitButtonLeftIconSize,
  splitButtonRightIconSize,
} from "../../core-types/split-button/split-button.constants";
import {
  SplitButtonProps as CoreSplitButtonProps,
  SplitButtonItemProps as CoreSplitButtonOptionProps,
} from "../../core-types/split-button/split-button.interface";
import Badge from "../badge/Badge";
import { Dropdown } from "../dropdown/Dropdown";
import { DropdownItem } from "../dropdown/dropdownItem/DropdownItem";
import Icon from "../icon/Icon";
import { RegularIcons, TogglableIcons } from "../icon/IconMap";
import { concatClassNames } from "../utils";

import style from "./SplitButton.module.scss";

interface SplitButtonOption extends CoreSplitButtonOptionProps {
  onClick?: (e: MouseEvent<HTMLElement> | KeyboardEvent<HTMLElement>) => void;
}

interface SplitButtonProps
  extends Omit<CoreSplitButtonProps, "options">, Omit<ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> {
  onClick?: (e: MouseEvent<HTMLButtonElement>) => void;
  icon?: keyof typeof RegularIcons | keyof typeof TogglableIcons;
  options: SplitButtonOption[];
}

const SplitButton = forwardRef<HTMLElement | HTMLButtonElement, SplitButtonProps>(
  (
    {
      appearance = "primary",
      size = "m",
      label,
      compactSpacing = false,
      position = "bottom-start",
      className,
      icon,
      onClick,
      disabled,
      ariaLabelRight,
      options,
      showBadge,
      badgeContent,
      badgeIcon,
      badgeType,
      badgeCount,
      badgeSize,
      ...props
    }: SplitButtonProps,
    ref,
  ) => {
    const [isDropdownOpen, setIsDropdownOpen] = useState<boolean>(false);

    const rightButtonRef = useRef<HTMLButtonElement>(null);
    const leftButtonRef = useRef<HTMLButtonElement>(null);
    const menuRef = useRef<HTMLDivElement>(null);

    const [internalPosition, internalAlignment] = position.split("-") as [
      DropdownProps["position"],
      DropdownProps["alignment"],
    ];

    const handleKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
      if ([ENTER_KEY].includes(e.key)) {
        e.preventDefault();
      }
    };

    const handleKeyUp = (e: KeyboardEvent<HTMLButtonElement>) => {
      if ([ENTER_KEY, ARROW_DOWN_KEY].includes(e.key)) {
        setIsDropdownOpen(true);
      }
    };

    return (
      <div
        className={concatClassNames(style.splitButtonContainer, className)}
        data-size={size}
        data-compact-spacing={compactSpacing}
        ref={ref as ForwardedRef<HTMLDivElement>}
      >
        <button
          type="button"
          className={style.splitButtonLeft}
          data-appearance={appearance}
          data-size={size}
          onClick={onClick}
          disabled={disabled}
          data-testid="Main action button"
          {...props}
          ref={leftButtonRef}
        >
          {icon && <Icon name={icon} size={splitButtonLeftIconSize[size]} />}
          <p data-size={size} className={style.splitButtonLabel}>
            {label}
          </p>
        </button>
        <div className={style.splitButtonDivider} data-appearance={appearance} data-disabled={disabled}></div>
        <Dropdown
          ref={menuRef}
          autoClose
          dropdownId={"tab-dropdown"}
          onClose={() => setIsDropdownOpen(false)}
          offset={0}
          data-testid="Menu container"
          position={internalPosition}
          alignment={internalAlignment}
          trigger={
            shouldDisplayBadge({ showBadge: !!showBadge, badgeContent, badgeCount, badgeIcon }) ? (
              <Badge count={badgeCount} content={badgeContent} badgeType={badgeType} icon={badgeIcon} size={badgeSize}>
                <button
                  type="button"
                  aria-haspopup="menu"
                  aria-expanded={isDropdownOpen}
                  aria-label={ariaLabelRight}
                  className={style.splitButtonRight}
                  data-active={isDropdownOpen}
                  data-compact-spacing={compactSpacing}
                  data-appearance={appearance}
                  data-size={size}
                  data-testid="Menu button"
                  disabled={disabled}
                  onClick={() => setIsDropdownOpen(true)}
                  onKeyDown={handleKeyDown}
                  onKeyUp={handleKeyUp}
                  {...props}
                  ref={rightButtonRef}
                >
                  <div className={style.splitButtonRightIconContainer}>
                    <Icon name="arrow-chevron-down" size={splitButtonRightIconSize[size]} />
                  </div>
                </button>
              </Badge>
            ) : (
              <button
                type="button"
                aria-haspopup="menu"
                aria-expanded={isDropdownOpen}
                aria-label={ariaLabelRight}
                className={style.splitButtonRight}
                data-active={isDropdownOpen}
                data-compact-spacing={compactSpacing}
                data-appearance={appearance}
                data-size={size}
                data-testid="Menu button"
                disabled={disabled}
                onClick={() => setIsDropdownOpen(true)}
                onKeyDown={handleKeyDown}
                onKeyUp={handleKeyUp}
                {...props}
                ref={rightButtonRef}
              >
                <div className={style.splitButtonRightIconContainer}>
                  <Icon name="arrow-chevron-down" size={splitButtonRightIconSize[size]} />
                </div>
              </button>
            )
          }
          isOpen={isDropdownOpen}
        >
          {options.map((option, idx) => (
            <DropdownItem
              key={`${option.id}-dropdown-${idx}`}
              id={option.id}
              label={option.label}
              onClick={option.onClick}
              disabled={option.disabled}
              leftIcon={option.icon}
              badgeContent={option.badgeContent}
              badgeIcon={option.badgeIcon}
              badgeType={option.badgeType}
              showBadge={option.showBadge}
              badgeCount={option.badgeCount}
            />
          ))}
        </Dropdown>
      </div>
    );
  },
);

export default SplitButton;

// packages/angular/projects/ds-rte-lib/src/lib/components/split-button/split-button.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input, signal, OnInit, OnDestroy } from "@angular/core";
import { BadgeContent, BadgeSize, BadgeType } from "@rte-ds/core/components/badge/badge.interface";
import { shouldDisplayBadge } from "@rte-ds/core/components/badge/badge.utils";
import { Alignment, Position } from "@rte-ds/core/components/common/common-types";
import {
  splitButtonLeftIconSize,
  splitButtonRightIconSize,
} from "@rte-ds/core/components/split-button/split-button.constants";
import {
  SplitButtonAppearance,
  SplitButtonItemProps,
  SplitButtonPosition,
  SplitButtonSize,
} from "@rte-ds/core/components/split-button/split-button.interface";
import { ARROW_DOWN_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";

import { BadgeDirective } from "../badge/badge.directive";
import { DropdownModule } from "../dropdown";
import { IconComponent } from "../icon/icon.component";
import { RegularIconIdKey, TogglableIconIdKey } from "../icon/icon.service";

@Component({
  selector: "rte-split-button",
  imports: [CommonModule, IconComponent, DropdownModule, BadgeDirective],
  standalone: true,
  templateUrl: "./split-button.component.html",
  styleUrl: "./split-button.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SplitButtonComponent implements OnInit, OnDestroy {
  readonly appearance = input<SplitButtonAppearance>("primary");
  readonly size = input<SplitButtonSize>("m");
  readonly label = input.required<string>();
  readonly compactSpacing = input(false);
  readonly position = input<SplitButtonPosition>("bottom-start");
  readonly icon = input<RegularIconIdKey | TogglableIconIdKey | null>(null);
  readonly disabled = input(false);
  readonly ariaLabelRight = input<string>();
  readonly options = input<SplitButtonItemProps[]>([]);
  readonly badgeType = input<BadgeType>();
  readonly showBadge = input<boolean>(false);
  readonly badgeContent = input<BadgeContent>();
  readonly badgeCount = input<number | undefined>(undefined);
  readonly badgeIcon = input<RegularIconIdKey | TogglableIconIdKey>("notification");
  readonly badgeSize = input<BadgeSize>("m");

  readonly splitButtonLeftIconSize = computed(() => splitButtonLeftIconSize[this.size()]);
  readonly splitButtonRightIconSize = computed(() => splitButtonRightIconSize[this.size()]);

  readonly isOpen = signal(false);

  readonly internalPosition = computed(() => {
    return this.position().split("-")[0] as Position;
  });
  readonly internalAlignment = computed(() => {
    return this.position().split("-")[1] as Alignment;
  });

  readonly hasBadge = computed(() =>
    shouldDisplayBadge({
      showBadge: !!this.showBadge(),
      badgeContent: this.badgeContent(),
      badgeCount: this.badgeCount(),
      badgeIcon: this.badgeIcon(),
    }),
  );

  handleClickOutside(event: MouseEvent): void {
    const target = event.target as Element;
    const allDropdowns = document.querySelectorAll("[data-dropdown-id]");
    const clickedInside = Array.from(allDropdowns).some((dropdown) => dropdown.contains(target));

    if (!clickedInside) {
      this.isOpen.set(false);
    }
  }

  ngOnInit(): void {
    window.addEventListener("click", this.handleClickOutside.bind(this));
  }

  ngOnDestroy(): void {
    window.removeEventListener("click", this.handleClickOutside.bind(this));
  }

  handleKeyDownOnRightButton(event: KeyboardEvent): void {
    this.handleKeyDown(event, ARROW_DOWN_KEY, () => this.isOpen.set(true));
    this.handleKeyDown(event, SPACE_KEY, () => this.isOpen.set(true));
    this.handleKeyDown(event, "Escape", () => this.isOpen.set(false));
  }

  handleKeyDownOnMenu(event: KeyboardEvent): void {
    this.handleKeyDown(event, "Escape", () => this.isOpen.set(false));
  }

  private handleKeyDown(event: KeyboardEvent, key: string, callback: () => void): void {
    if (event.key === key) {
      event.preventDefault();
      callback();
    }
  }
}
