// packages/react/src/components/button/Button.tsx
import { ButtonProps as CoreButtonProps } from "@rte-ds/core/components/button/button.interface";
import { ButtonBadgeSizeMapping } from "@rte-ds/core/components/button/common/common-button.constants";
import { forwardRef } from "react";

import Badge from "../badge/Badge";
import { concatClassNames } from "../utils";

import style from "./Button.module.scss";

interface ButtonProps
  extends Omit<CoreButtonProps, "disabled">, Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "onClick"> {
  onClick?: (e: React.MouseEvent<HTMLButtonElement>) => void;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      size = "m",
      label,
      variant = "primary",
      className = "",
      onClick,
      type = "button",
      badgeContent,
      badgeCount,
      badgeType,
      badgeIcon,
      ...props
    },
    ref,
  ) => {
    const shouldDisplayBadge = (badgeCount > 0 && badgeContent === "number") || (badgeContent === "icon" && badgeIcon);

    if (shouldDisplayBadge) {
      return (
        <Badge
          badgeType={badgeType}
          size={ButtonBadgeSizeMapping[size]}
          content={size === "s" ? "empty" : badgeContent}
          count={badgeCount}
          icon={badgeIcon}
        >
          <button
            ref={ref}
            type={type}
            className={concatClassNames(style.button, className)}
            data-size={size}
            data-variant={variant}
            onClick={onClick}
            {...props}
          >
            <span data-size={size} className={style.label}>
              {label}
            </span>
          </button>
        </Badge>
      );
    } else {
      return (
        <button
          ref={ref}
          type={type}
          className={concatClassNames(style.button, className)}
          data-size={size}
          data-variant={variant}
          onClick={onClick}
          {...props}
        >
          <span data-size={size} className={style.label}>
            {label}
          </span>
        </button>
      );
    }
  },
);

export default Button;

// packages/angular/projects/ds-rte-lib/src/lib/components/button/button.component.ts
import { ChangeDetectionStrategy, Component, computed, HostBinding, input } from "@angular/core";
import { BadgeContent } from "@rte-ds/core/components/badge/badge.interface";
import { ButtonSize, ButtonVariant } from "@rte-ds/core/components/button/common/common-button";

@Component({
  selector: "button[rteButton]",
  standalone: true,
  templateUrl: "./button.component.html",
  styleUrl: "./button.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent {
  readonly rteButtonVariant = input<ButtonVariant>("primary");
  readonly rteButtonSize = input<ButtonSize>("m");
  readonly rteBadgeCount = input<number>();
  readonly rteBadgeContent = input<BadgeContent>();

  @HostBinding("class") get classes() {
    return `rte-button ${this.rteButtonVariant()} size-${this.rteButtonSize()}`;
  }

  readonly shouldDisplayBadge = computed(() => {
    const count = this.rteBadgeCount();
    const content = this.rteBadgeContent();

    return (count && count > 0 && content === "number") || content === "icon";
  });
}
