// packages/angular/projects/ds-rte-lib/src/lib/components/banner/banner.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  input,
  output,
  signal,
  SimpleChanges,
  OnInit,
  OnChanges,
  computed,
} from "@angular/core";
import { BannerPosition, BannerType } from "@rte-ds/core/components/banner/banner.interface";

import { ButtonComponent } from "../button/button.component";
import { IconComponent } from "../icon/icon.component";
import { IconButtonComponent } from "../icon-button/icon-button.component";

@Component({
  selector: "rte-banner",
  imports: [CommonModule, IconComponent, IconButtonComponent, ButtonComponent],
  standalone: true,
  templateUrl: "./banner.component.html",
  styleUrl: "./banner.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BannerComponent implements OnInit, OnChanges {
  readonly type = input<BannerType>("info");
  readonly message = input.required<string>();
  readonly position = input<BannerPosition>("push");
  readonly title = input<string>();
  readonly closable = input<boolean>(false);
  readonly isOpen = input<boolean>(true);
  readonly actionLabel = input<string>();

  readonly click = output<void>();

  readonly visible = signal(false);
  readonly rendering = signal(false);

  readonly close = output<void>();

  readonly iconTypeMap: Record<string, string> = {
    info: "info",
    error: "dangerous",
    success: "check-circle",
    warning: "warning",
  };

  readonly iconName = computed(() => {
    return this.iconTypeMap[this.type()];
  });

  ngOnInit() {
    this.visible.set(this.isOpen());
    this.rendering.set(this.isOpen());
    if (this.closable() === false && this.position() === "overlay") {
      console.warn("Banner: 'closable' and 'close' props must be set when 'position' has 'overlay' value.");
      return;
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes["isOpen"]) {
      if (this.isOpen()) this.openBanner();
      else {
        this.closeBanner();
      }
    }
  }

  clickAction() {
    this.click.emit();
  }

  closeBanner() {
    this.visible.set(false);
    setTimeout(() => {
      this.rendering.set(false);
      this.close.emit();
    }, 200);
  }

  private openBanner() {
    if (this.rendering()) return;
    this.rendering.set(true);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => this.visible.set(true));
    });
  }
}

// packages/react/src/components/banner/Banner.tsx
import { BannerProps as CoreBannerProps } from "@rte-ds/core/components/banner/banner.interface";
import { forwardRef, useEffect, useState } from "react";

import useAnimatedMount from "../../hooks/useAnimatedMount";
import Button from "../button/Button";
import Icon from "../icon/Icon";
import IconButton from "../iconButton/IconButton";
import { concatClassNames } from "../utils";

import style from "./Banner.module.scss";

interface BannerProps extends CoreBannerProps, React.HTMLAttributes<HTMLDivElement> {}

const Banner = forwardRef<HTMLDivElement, BannerProps>(
  (
    {
      title,
      message,
      type = "alert",
      closable = false,
      onClose,
      position = "push",
      actionCallback,
      actionLabel,
      className = "",
      isOpen = true,
      ...props
    },
    ref,
  ) => {
    const [isInternalOpen, setIsInternalOpen] = useState(isOpen);
    const ariaRole = type === "error" ? "alert" : "status";
    const { shouldRender, isAnimating } = useAnimatedMount(isInternalOpen, 200);

    const iconTypeMap: Record<string, string> = {
      info: "info",
      error: "dangerous",
      success: "check-circle",
      warning: "warning",
    };

    useEffect(() => {
      setIsInternalOpen(isOpen);
    }, [isOpen]);

    if (closable === false && position === "overlay") {
      console.warn("Banner: 'closable' and 'onClose' props must be set when 'position' has 'overlay' value.");
      return null;
    }

    const handleOnClose = () => {
      setIsInternalOpen(false);
      onClose?.();
    };

    return (
      shouldRender && (
        <section
          role={ariaRole}
          className={concatClassNames(style["banner"], className)}
          ref={ref}
          data-type={type}
          data-position={position}
          data-open={isAnimating || undefined}
          {...props}
        >
          <div className={style["banner-icon"]}>
            <Icon name={iconTypeMap[type]} size={32} />
          </div>
          <div className={style["banner-content"]}>
            {title && <span className={style["banner-title"]}>{title}</span>}
            {message && (
              <div className={style["banner-message"]}>
                <span>{message}</span>
              </div>
            )}
          </div>
          {actionCallback && actionLabel && (
            <Button label={actionLabel} onClick={actionCallback} variant="text" aria-label={actionLabel} size="s" />
          )}
          {closable && (
            <div className={style["banner-close-icon"]}>
              <IconButton variant="neutral" name="close" onClick={handleOnClose} aria-label="close banner" />
            </div>
          )}
        </section>
      )
    );
  },
);

export default Banner;
