// packages/react/.storybook/template/ThemeSelector/ThemeSelector.tsx
import { Mode, Theme } from "@rte-ds/core/common/common-types";
import { Chip, IconButton } from "@rte-ds/react";
import { useState } from "react";

import styles from "./ThemeSelector.module.scss";

const ThemeSelector = () => {
  const [currentMode, setCurrentMode] = useState<Mode>("light");
  const [currentTheme, setCurrentTheme] = useState<Theme>("bleu_iceberg");

  const switchMode = (mode: "light" | "dark") => {
    document.querySelector("html")?.setAttribute("data-mode", mode);
    setCurrentMode(mode);
  };

  const switchTheme = (theme: "bleu_iceberg" | "vert_foret" | "violet") => {
    document.querySelector("html")?.setAttribute("data-theme", theme);
    setCurrentTheme(theme);
  };

  const themes = [
    { id: "bleu_iceberg", label: "Bleu Iceberg" },
    { id: "violet", label: "Violet" },
    { id: "vert_foret", label: "Vert Forêt" },
  ];

  const handleClick = (event: React.MouseEvent<HTMLSpanElement> | React.KeyboardEvent<HTMLSpanElement>) => {
    const clickedChipId = event.currentTarget.id as "bleu_iceberg" | "vert_foret" | "violet";
    switchTheme(clickedChipId);
  };

  return (
    <div className={styles["theme-selector"]}>
      <div className={styles["theme-selector__chips"]} role="radiogroup">
        {themes.map(({ id, label }) => (
          <Chip
            id={id}
            key={id}
            label={label}
            selected={currentTheme === id}
            onClick={handleClick}
            type="single"
            className="chip"
          />
        ))}
      </div>
      <div style={{ display: "flex" }}>
        <IconButton
          name={currentMode === "light" ? "mode-dark" : "mode-light"}
          aria-label={"Toggle Theme Mode"}
          onClick={() => switchMode(currentMode === "light" ? "dark" : "light")}
          data-testid="mode-switcher"
        />
      </div>
    </div>
  );
};

export default ThemeSelector;

// packages/angular/.storybook/template/theme-selector/theme-selector.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, signal } from "@angular/core";
import { Mode, Theme } from "@rte-ds/core/common/common-types";

import { ChipComponent } from "../../../projects/ds-rte-lib/src/lib/components/chip/chip.component";
import { IconButtonComponent } from "../../../projects/ds-rte-lib/src/lib/components/icon-button/icon-button.component";

@Component({
  selector: "rte-theme-selector",
  imports: [ChipComponent, CommonModule, IconButtonComponent],
  standalone: true,
  templateUrl: "./theme-selector.component.html",
  styleUrl: "./theme-selector.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThemeSelectorComponent {
  readonly themes: Array<{ id: Theme; label: string }> = [
    { id: "bleu_iceberg", label: "Bleu Iceberg" },
    { id: "violet", label: "Violet" },
    { id: "vert_foret", label: "Vert Forêt" },
  ];

  readonly selectedTheme = signal<Theme>("bleu_iceberg");

  readonly selectedMode = signal<Mode>("light");

  readonly iconName = computed(() => (this.selectedMode() === "light" ? "mode-dark" : "mode-light"));
  readonly nextMode = computed<Mode>(() => (this.selectedMode() === "light" ? "dark" : "light"));

  selectTheme(theme: Theme): void {
    this.selectedTheme.set(theme);
    document.documentElement.setAttribute("data-theme", theme);
  }

  selectMode(mode: Mode): void {
    this.selectedMode.set(mode);
    document.documentElement.setAttribute("data-mode", mode);
  }
}
