// packages/angular/projects/ds-rte-lib/src/lib/components/radio-button/radio-button.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, input } from "@angular/core";
import { labelSize } from "@rte-ds/core/components/radio-button/radio-button.constants";

@Component({
  selector: "rte-radio-button",
  imports: [CommonModule],
  standalone: true,
  templateUrl: "./radio-button.component.html",
  styleUrl: "./radio-button.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RadioButtonComponent {
  readonly label = input("");
  readonly groupName = input("");
  readonly showLabel = input(true);
  readonly disabled = input(false);
  readonly error = input(false);
  readonly readOnly = input(false);
  labelSize = labelSize;

  readonly isDisplayed = computed(() => !(this.disabled() && this.error()));
}

// packages/react/src/components/radioButton/RadioButton.tsx
import { labelSize } from "@rte-ds/core/components/radio-button/radio-button.constants";
import { RadioButtonProps as CoreRadioButtonProps } from "@rte-ds/core/components/radio-button/radio-button.interface";
import React, { forwardRef } from "react";

import { concatClassNames } from "../utils";

import style from "./RadioButton.module.scss";

interface RadioButtonProps extends CoreRadioButtonProps, React.InputHTMLAttributes<HTMLInputElement> {}

const RadioButton = forwardRef<HTMLInputElement, RadioButtonProps>(
  (
    { label, groupName, showLabel = true, disabled = false, error = false, readOnly = false, className = "", ...props },
    ref,
  ) => {
    if (disabled && error) {
      return;
    }

    return (
      <div className={style.radioButtonContainer}>
        <input
          ref={ref}
          type="radio"
          id={label}
          value={label}
          size={labelSize}
          name={groupName}
          className={concatClassNames(style.radioButton, className)}
          disabled={disabled}
          data-error={error}
          data-read-only={readOnly}
          {...props}
        />
        {showLabel && (
          <label
            htmlFor={label}
            className={concatClassNames(style.radioButtonLabel, className)}
            data-disabled={disabled}
            data-error={error}
            data-read-only={readOnly}
            data-show-label={showLabel}
          >
            {label}
          </label>
        )}
      </div>
    );
  },
);

export default RadioButton;
