// packages/react/src/components/select/Select.tsx
import {
  MIN_SELECT_WIDTH,
  SELECT_DROPDOWN_OFFSET,
  THRESHOLD_BOTTOM_POSITION,
} from "@rte-ds/core/components/select/select.constants";
import { SelectProps as coreSelectProps } from "@rte-ds/core/components/select/select.interface";
import { ENTER_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";
import { forwardRef, useEffect, useRef, useState } from "react";

import AssistiveText from "../assistivetext/AssistiveText";
import { Dropdown } from "../dropdown/Dropdown";
import { DropdownItem } from "../dropdown/dropdownItem/DropdownItem";
import Icon from "../icon/Icon";
import IconButton from "../iconButton/IconButton";
import RequiredIndicator from "../requiredindicator/RequiredIndicator";
import Tooltip from "../tooltip/Tooltip";
import { concatClassNames } from "../utils";

import styles from "./Select.module.scss";

interface SelectProps extends coreSelectProps {
  labelId?: string;
  tooltipTextLabel?: string;
}

const Select = forwardRef<HTMLDivElement, SelectProps>(
  (
    {
      id,
      label,
      labelId,
      labelPosition = "top",
      required = false,
      value,
      showLabel = true,
      isError,
      assistiveAppearance = "description",
      showAssistiveIcon = false,
      assistiveTextLink,
      showLabelRequirement = false,
      assistiveTextLabel,
      onClear,
      onChange,
      options = [],
      disabled,
      readonly,
      showResetButton,
      width = MIN_SELECT_WIDTH,
      multiple = false,
      multipleValue,
      onMultipleChange,
      tooltipTextLabel,
    },
    ref,
  ) => {
    const [internalValue, setInternalValue] = useState(value || "");
    const [internalMultipleValue, setInternalMultipleValue] = useState<string[]>(multipleValue || []);

    const [isActive, setIsActive] = useState(false);

    const selectRef = useRef<HTMLDivElement | null>(null);

    const selectRefCallback = (node: HTMLDivElement | null) => {
      selectRef.current = node;
      if (typeof ref === "function") {
        ref(node);
      } else if (ref) {
        ref.current = node;
      }
    };

    const hasValue = multiple ? internalMultipleValue.length > 0 : !!internalValue;
    const shouldDisplayClearButton = showResetButton && hasValue && !readonly && !disabled;

    const currentOption = options.find((option) => option.value === internalValue);
    const currentOptionLabel = currentOption?.label;
    const currentOptionIcon = currentOption?.icon;

    const getMultipleDisplayValue = () => {
      if (internalMultipleValue.length === 0) return "";
      if (internalMultipleValue.length === 1) {
        return options.find((opt) => opt.value === internalMultipleValue[0])?.label || "";
      }
      return `${internalMultipleValue.length} sélectionnés`;
    };

    const isOptionSelected = (optionValue: string) => {
      return internalMultipleValue.includes(optionValue);
    };

    const handleMultipleSelect = (optionValue: string) => {
      const newValues = isOptionSelected(optionValue)
        ? internalMultipleValue.filter((v) => v !== optionValue)
        : [...internalMultipleValue, optionValue];
      setInternalMultipleValue(newValues);
      onMultipleChange?.(newValues);
    };

    const shouldDisplayErrorIcon = isError && !disabled && !readonly;

    const computeDropdownPosition = () => {
      const selectElement = selectRef.current;
      if (selectElement) {
        const rect = selectElement.getBoundingClientRect();
        const spaceBelow = window.innerHeight - rect.bottom;
        return spaceBelow >= THRESHOLD_BOTTOM_POSITION ? "bottom" : "top";
      }
      return "bottom";
    };

    const handleOnClick = () => {
      if (selectRef.current) {
        if (disabled) {
          return;
        }
        selectRef.current.focus();
        setIsActive(!isActive);
      }
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
      if (document.activeElement === selectRef.current) {
        if (e.key === SPACE_KEY || e.key === ENTER_KEY) {
          e.preventDefault();
          handleOnClick();
        }
      }
    };

    const handleOnClear = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
      e.stopPropagation();
      if (multiple) {
        setInternalMultipleValue([]);
        onMultipleChange?.([]);
      } else {
        handleOnChange("");
      }
      onClear?.();
      selectRef.current?.focus();
    };

    const handleOnChange = (newValue: string) => {
      setInternalValue(newValue);
      onChange?.(newValue);
      setIsActive(false);
    };

    useEffect(() => {
      setInternalValue(value || "");
    }, [value]);

    useEffect(() => {
      setInternalMultipleValue(multipleValue || []);
    }, [multipleValue]);

    const content = (
      <div className={styles["select-container"]} data-label-position={labelPosition}>
        {showLabel && labelPosition === "side" && (
          <label htmlFor={id} id={labelId} className={styles["select-label"]}>
            {label}
            <RequiredIndicator required={required} showLabelRequirement={showLabelRequirement} />
          </label>
        )}
        <div className={styles["select-header"]}>
          {showLabel && labelPosition === "top" && (
            <label htmlFor={id} id={labelId} className={styles["select-label"]}>
              {label}
              <RequiredIndicator required={required} showLabelRequirement={showLabelRequirement} />
            </label>
          )}
          <Dropdown
            style={{ width: selectRef.current?.offsetWidth }}
            dropdownId={id + "-dropdown"}
            onClose={() => {
              setIsActive(false);
            }}
            offset={SELECT_DROPDOWN_OFFSET}
            trigger={
              <div
                ref={selectRefCallback}
                aria-expanded={isActive}
                aria-labelledby={labelId}
                data-error={isError ? "true" : "false"}
                data-active={isActive ? "true" : "false"}
                data-disabled={disabled ? "true" : "false"}
                data-read-only={readonly ? "true" : "false"}
                id={id}
                className={styles["select-wrapper"]}
                role="combobox"
                tabIndex={disabled ? -1 : 0}
                onClick={handleOnClick}
                onKeyDown={handleKeyDown}
                style={{ width: width }}
              >
                <div className={styles["select-content"]}>
                  {shouldDisplayErrorIcon && <Icon name="error" className={styles["error-icon"]} />}
                  <div className={styles["select-value"]}>
                    {!multiple && currentOptionIcon && (
                      <Icon name={currentOptionIcon} className={styles["select-value-icon"]} />
                    )}
                    <span>{multiple ? getMultipleDisplayValue() : currentOptionLabel}</span>
                  </div>
                  <div className={styles["select-right-icons"]}>
                    {shouldDisplayClearButton && (
                      <IconButton
                        name="cancel"
                        variant="neutral"
                        className={concatClassNames(styles["icon-button"], styles["clear-icon"])}
                        onClick={handleOnClear}
                        disabled={disabled}
                      />
                    )}
                    <Icon
                      name={isActive ? "arrow-chevron-up" : "arrow-chevron-down"}
                      data-testid="trigger-icon"
                      className={styles["trigger-icon"]}
                    />
                  </div>
                </div>
              </div>
            }
            isOpen={isActive}
            position={computeDropdownPosition()}
          >
            {options.length === 0 && <DropdownItem label="No options available" onClick={() => {}} />}
            {multiple
              ? options.map(({ value, label, icon }, index) => (
                  <li
                    key={index + value}
                    className={styles["dropdown-item-multiple"]}
                    role="option"
                    aria-selected={isOptionSelected(value)}
                    onClick={() => !readonly && handleMultipleSelect(value)}
                    tabIndex={readonly ? -1 : 0}
                    data-read-only={readonly ? "true" : "false"}
                  >
                    <Icon
                      name={isOptionSelected(value) ? "checkbox" : "checkbox-empty"}
                      appearance={isOptionSelected(value) ? "filled" : "outlined"}
                      className={styles["checkbox-icon"]}
                    />
                    {icon && <Icon name={icon} className={styles["option-icon"]} />}
                    <span>{label}</span>
                  </li>
                ))
              : options.map(({ value, label, icon }, index) => (
                  <DropdownItem
                    key={index + value}
                    label={label}
                    leftIcon={icon}
                    isSelected={value === internalValue}
                    disabled={readonly}
                    onClick={() => {
                      if (!readonly) {
                        handleOnChange(value);
                      }
                    }}
                  />
                ))}
          </Dropdown>

          {assistiveTextLabel && (
            <AssistiveText
              label={assistiveTextLabel}
              appearance={isError ? "error" : assistiveAppearance}
              showIcon={showAssistiveIcon}
              href={assistiveTextLink}
              width={width}
            />
          )}
        </div>
      </div>
    );

    return (
      <>
        {tooltipTextLabel ? (
          <Tooltip alignment="start" arrow label={tooltipTextLabel} position="bottom">
            {content}
          </Tooltip>
        ) : (
          content
        )}
      </>
    );
  },
);

export default Select;

// packages/angular/projects/ds-rte-lib/src/lib/components/select/select.component.ts
import { CommonModule } from "@angular/common";
import {
  Component,
  input,
  computed,
  output,
  signal,
  viewChild,
  ElementRef,
  ChangeDetectionStrategy,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import { REQUIREMENT_INDICATOR_VALUE } from "@rte-ds/core/components/required-indicator/required-indicator.constant";
import {
  SELECT_DROPDOWN_OFFSET,
  THRESHOLD_BOTTOM_POSITION,
  MIN_SELECT_WIDTH,
} from "@rte-ds/core/components/select/select.constants";
import { SelectProps } from "@rte-ds/core/components/select/select.interface";
import { ENTER_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";

import { AssistiveTextComponent } from "../assistive-text/assistive-text.component";
import { DropdownModule } from "../dropdown";
import { IconComponent } from "../icon/icon.component";
import { IconButtonComponent } from "../icon-button/icon-button.component";

@Component({
  selector: "rte-select",
  imports: [CommonModule, IconComponent, DropdownModule, IconButtonComponent, AssistiveTextComponent],
  standalone: true,
  templateUrl: "./select.component.html",
  styleUrl: "./select.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: SelectComponent,
      multi: true,
    },
  ],
})
export class SelectComponent {
  readonly id = input<string>();
  readonly name = input<string>();
  readonly ariaLabelledby = input<string>();
  readonly label = input<string>();
  readonly labelId = input<string>();
  readonly labelPosition = input<SelectProps["labelPosition"]>("top");
  readonly assistiveTextLabel = input<string>();
  readonly assistiveTextAppearance = input<SelectProps["assistiveAppearance"]>("description");
  readonly assistiveTextLink = input<string>();
  readonly required = input<boolean>(false);
  readonly showLabelRequirement = input<boolean>(false);
  readonly disabled = input<boolean>(false);
  readonly readOnly = input<boolean>(false);
  readonly value = input<string>();
  readonly options = input<SelectProps["options"]>([]);
  readonly isError = input<boolean>(false);
  readonly showAssistiveIcon = input<boolean>(false);
  readonly showResetButton = input<boolean>(false);
  readonly width = input<number>(MIN_SELECT_WIDTH);

  readonly selectRef = viewChild<ElementRef<HTMLElement>>("selectRef");
  readonly buttonsContainerRef = viewChild<ElementRef<HTMLElement>>("buttonsContainerRef");

  readonly selectDropdownOffset = SELECT_DROPDOWN_OFFSET;

  readonly computedWidth = computed(() => {
    return `${this.width()}px`;
  });

  readonly clearButton = computed(() => {
    return this.buttonsContainerRef()?.nativeElement.querySelector(
      ".rte-icon-button.clear-button",
    ) as HTMLElement | null;
  });

  readonly dropdownPosition = computed<"bottom" | "top">(() => {
    const selectElement = this.selectRef()?.nativeElement;
    if (selectElement) {
      const rect = selectElement.getBoundingClientRect();
      const spaceBelow = window.innerHeight - rect.bottom;
      return spaceBelow >= THRESHOLD_BOTTOM_POSITION ? "bottom" : "top";
    }
    return "bottom";
  });

  readonly internalValue = signal(this.value());

  readonly requirementIndicatorValue = computed(() =>
    this.required()
      ? this.showLabelRequirement()
        ? REQUIREMENT_INDICATOR_VALUE.required
        : REQUIREMENT_INDICATOR_VALUE.requiredIcon
      : REQUIREMENT_INDICATOR_VALUE.optional,
  );

  readonly valueChange = output<Event>();

  readonly currentOptionLabel = computed(() => {
    return this.options().find((option) => option.value === this.internalValue())?.label;
  });

  readonly isAssistiveTextLinkVisible = computed(() => {
    return this.assistiveTextAppearance() === "link" && this.assistiveTextLink() !== undefined;
  });

  readonly formattedOptions = computed(() => {
    return this.options().map(({ value, label }) => ({
      id: value,
      label: label,
      selected: value === this.internalValue(),
    }));
  });

  readonly shouldDisplayClearButton = computed(
    () => this.showResetButton() && !!this.internalValue() && !this.disabled(),
  );

  readonly shouldDisplayErrorIcon = computed(() => this.isError() && !this.disabled() && !this.readOnly());

  readonly isActive = signal(false);

  readonly selectWidth = computed(() => {
    const nativeElement = this.selectRef()?.nativeElement;
    if (nativeElement) {
      return nativeElement.getBoundingClientRect().width;
    }
    return null;
  });

  handleOnClickTrigger() {
    if (this.readOnly() || this.disabled()) {
      return;
    }
    this.toggleDropdown();
  }

  handleOnKeyDownTrigger(event: KeyboardEvent) {
    if (this.readOnly() || this.disabled()) {
      return;
    }
    if (this.shouldDisplayClearButton()) {
      const clearButton = this.buttonsContainerRef()?.nativeElement.children[0].children[0];
      const isClearButtonFocused = document.activeElement === clearButton;
      if (isClearButtonFocused && (event.key === SPACE_KEY || event.key === ENTER_KEY)) {
        this.clearSelection(event);
        return;
      }
    }

    if (event.key === SPACE_KEY || event.key === ENTER_KEY) {
      this.toggleDropdown();
    }
  }

  handleOnClickClearButton(event: Event): void {
    if (this.readOnly() || this.disabled()) {
      return;
    }
    event.preventDefault();
    this.clearSelection(event);
  }

  handleOnClickItem(id: string) {
    if (this.readOnly() || this.disabled()) {
      return;
    }
    this.internalValue.set(id);
    const event = new CustomEvent<{ target: { value: string } }>("change", {
      bubbles: true,
      detail: { target: { value: id } },
    });
    this.valueChange.emit(event);
    this.isActive.set(!this.isActive());
    this.selectRef()?.nativeElement.focus();
  }

  handleOnClosingDropdown() {
    this.isActive.set(false);
  }

  handleOnClickOutside() {
    this.isActive.set(false);
  }

  private toggleDropdown() {
    this.isActive.set(!this.isActive());
    if (this.isActive()) {
      this.selectRef()?.nativeElement.dispatchEvent(new Event("openDropdown"));
    } else {
      this.selectRef()?.nativeElement.dispatchEvent(new Event("closeDropdown"));
    }
  }

  private clearSelection(event: Event) {
    this.internalValue.set(undefined);
    this.isActive.set(false);
    this.valueChange.emit(event);
    this.selectRef()?.nativeElement.dispatchEvent(new Event("clearContent"));
  }
}
