// packages/react/src/components/badge/Badge.tsx
import { BadgeProps as BadgePropsCore } from "@rte-ds/core/components/badge/badge.interface";
import {
  getBadgeIconSize,
  getDisplayCount,
  getShowBadge,
  getShowIcon,
  getShowText,
} from "@rte-ds/core/components/badge/badge.utils";
import { forwardRef } from "react";

import Icon from "../icon/Icon";
import { isValidIconName } from "../icon/IconMap";
import { concatClassNames } from "../utils";

import style from "./Badge.module.scss";

export interface BadgeProps extends BadgePropsCore, Omit<React.HTMLAttributes<HTMLDivElement>, "children" | "content"> {
  children?: React.ReactNode;
  icon?: string;
}

const Badge = forwardRef<HTMLDivElement, BadgeProps>(
  ({ badgeType = "brand", size = "m", content = "number", count, icon = "notification", children, ...props }, ref) => {
    if (content == "icon" && icon && !isValidIconName(icon)) {
      console.warn(`Badge: Invalid icon name "${icon}". Please use a valid icon key.`);
      return null;
    }

    const iconSize = getBadgeIconSize(size);

    const showIcon = getShowIcon({ size, content, iconSize });
    const showText = getShowText({ size, content, count });

    const showBadge = getShowBadge({ size, content, count, iconSize });
    const countOverflow = showText && getDisplayCount(count)?.length > 2;

    // TODO change when refactoring button with badge
    if (!children) {
      return (
        <div ref={ref} className={style.badgeContainer} {...props}>
          <div
            data-simple-badge="true"
            data-badge-type={badgeType}
            data-size={size}
            data-testid="badge"
            className={concatClassNames(
              style.badge,
              showBadge ? "" : style.hidden,
              countOverflow ? style.countOverflow : "",
            )}
          >
            {showIcon && <Icon name={icon} className={style.icon} size={iconSize} />}
            {showText && (
              <span className={style.count} key={count}>
                {getDisplayCount(count)}
              </span>
            )}
          </div>
        </div>
      );
    }

    return (
      <div ref={ref} className={style.badgeContainer} {...props}>
        <div
          data-badge-type={badgeType}
          data-size={size}
          data-testid="badge"
          className={concatClassNames(
            style.badge,
            showBadge ? "" : style.hidden,
            countOverflow ? style.countOverflow : "",
          )}
        >
          {showIcon && <Icon name={icon} className={style.icon} size={iconSize} />}
          {showText && (
            <span className={style.count} key={count}>
              {getDisplayCount(count)}
            </span>
          )}
        </div>
        {children}
      </div>
    );
  },
);

export default Badge;

// packages/angular/projects/ds-rte-lib/src/lib/components/badge/badge.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, ChangeDetectionStrategy } from "@angular/core";
import { BadgeContent, BadgeSize, BadgeType } from "@rte-ds/core/components/badge/badge.interface";
import {
  getBadgeIconSize,
  getDisplayCount,
  getShowBadge,
  getShowIcon,
  getShowText,
} from "@rte-ds/core/components/badge/badge.utils";

import { isValidIconName } from "../icon/icon-map";
import { IconComponent } from "../icon/icon.component";

@Component({
  selector: "rte-badge",
  imports: [CommonModule, IconComponent],
  standalone: true,
  templateUrl: "./badge.component.html",
  styleUrl: "./badge.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BadgeComponent {
  readonly badgeType = input<BadgeType>("brand");
  readonly badgeSize = input<BadgeSize>("m");
  readonly badgeContent = input<BadgeContent>("number");
  readonly count = input<number | undefined>();
  readonly icon = input<string>("notification");
  readonly simpleBadge = input<boolean>(false);

  readonly isValidIconName = computed(() => {
    const icon = this.icon();
    return isValidIconName(icon!);
  });

  readonly showIcon = computed(() =>
    getShowIcon({
      size: this.badgeSize(),
      content: this.badgeContent(),
      iconSize: this.iconSize(),
    }),
  );

  readonly showText = computed(() =>
    getShowText({
      size: this.badgeSize(),
      content: this.badgeContent(),
      count: this.count(),
    }),
  );

  readonly displayCount = computed(() => getDisplayCount(this.count()));
  readonly countOverflow = computed(() => this.showText() && this.displayCount().length > 2);
  readonly iconSize = computed(() => getBadgeIconSize(this.badgeSize()));

  readonly showBadge = computed(() =>
    getShowBadge({
      size: this.badgeSize(),
      content: this.badgeContent(),
      count: this.count(),
      iconSize: this.iconSize(),
    }),
  );
}
