// packages/angular/projects/ds-rte-lib/src/lib/components/breadcrumbs/breadcrumb-item/breadcrumb-item.component.ts
import { CommonModule } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  signal,
  AfterViewInit,
} from "@angular/core";
import { shouldDisplayBadge as coreShouldDisplayBadge } from "@rte-ds/core/components/badge/badge.utils";
import { BreadcrumbItemProps } from "@rte-ds/core/components/breadcrumbs/breadcrumbs.interface";

import { BadgeComponent } from "../../badge/badge.component";
import { LinkComponent } from "../../link/link.component";
import { TooltipDirective } from "../../tooltip/tooltip.directive";

@Component({
  selector: "rte-breadcrumb-item",
  imports: [CommonModule, LinkComponent, TooltipDirective, BadgeComponent],
  standalone: true,
  templateUrl: "./breadcrumb-item.component.html",
  styleUrl: "./breadcrumb-item.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BreadcrumbItemComponent implements AfterViewInit {
  readonly item = input<BreadcrumbItemProps>();
  readonly isLast = input<boolean>(false);
  readonly breadcrumbItemMaxWidth = input<number>();
  readonly initialScrollWidth = signal<number>(Number.MAX_VALUE);

  private elementRef = inject(ElementRef);

  readonly isEllipsisActive = computed((): boolean => {
    const maxValue = this.breadcrumbItemMaxWidth();
    if (maxValue) {
      return this.initialScrollWidth() >= maxValue;
    }
    return false;
  });

  readonly shouldDisplayBadge = computed((): boolean => {
    const item = this.item();
    if (!item) return false;
    const { showBadge, badgeContent, badgeCount, badgeIcon } = item;
    return coreShouldDisplayBadge({
      showBadge: !!showBadge,
      badgeContent,
      badgeCount,
      badgeIcon,
    });
  });

  readonly tooltipTriggerStyle = computed(() => {
    return `overflow: hidden; text-overflow: ellipsis; white-space: nowrap; ${this.breadcrumbItemMaxWidth() ? "max-width:" + this.breadcrumbItemMaxWidth() + "px" : ""}`;
  });

  readonly linkStyle = computed(() => {
    return `${this.breadcrumbItemMaxWidth() ? "max-width:" + this.breadcrumbItemMaxWidth() + "px" : ""}`;
  });

  ngAfterViewInit() {
    const el = this.elementRef.nativeElement.querySelector(".rte-breadcrumb-item");
    this.initialScrollWidth.set(el.scrollWidth);
  }
}

// packages/react/src/components/breadcrumbs/breadcrumbItem/BreadcrumbItem.tsx
import { shouldDisplayBadge as coreShouldDisplayBadge } from "@rte-ds/core/components/badge/badge.utils";
import { BreadcrumbProps } from "@rte-ds/core/components/breadcrumbs/breadcrumbs.interface";
import { useEffect, useRef, useState } from "react";

import Badge from "../../badge/Badge";
import Link from "../../link/Link";
import Tooltip from "../../tooltip/Tooltip";

import style from "./BreadcrumbItem.module.scss";

const BreadcrumbItem = ({ item, isLast, breadcrumbItemMaxWidth }: BreadcrumbProps) => {
  const [isEllipsisActive, setIsEllipsisActive] = useState<boolean>(false);
  const initialScrollWidth = useRef<number>();
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (ref.current) {
      initialScrollWidth.current = ref.current.querySelector("a")?.scrollWidth;
    }
  }, []);

  useEffect(() => {
    const computeIsEllipsisActive = () => {
      if (initialScrollWidth.current && breadcrumbItemMaxWidth) {
        setIsEllipsisActive(initialScrollWidth.current >= breadcrumbItemMaxWidth);
      }
    };
    computeIsEllipsisActive();
  }, [breadcrumbItemMaxWidth]);

  const { showBadge, badgeContent, badgeCount, badgeIcon, badgeType, badgeSize } = item;
  const shouldDisplayBadge = coreShouldDisplayBadge({ showBadge: !!showBadge, badgeContent, badgeCount, badgeIcon });

  return (
    <div key={item.link} className={style.breadcrumbItem} ref={ref}>
      {isLast ? (
        <>
          {isEllipsisActive ? (
            <Tooltip
              label={item.label}
              position="bottom"
              alignment="center"
              triggerStyles={{
                maxWidth: `${breadcrumbItemMaxWidth}px`,
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
              }}
            >
              <a
                role="link"
                aria-label={item.label}
                aria-current="page"
                tabIndex={-1}
                style={{ maxWidth: `${breadcrumbItemMaxWidth}px` }}
              >
                {item.label}
              </a>
              {shouldDisplayBadge && (
                <Badge
                  count={badgeCount}
                  content={badgeContent}
                  icon={badgeIcon}
                  badgeType={badgeType}
                  size={badgeSize}
                />
              )}
            </Tooltip>
          ) : (
            <>
              <a
                role="link"
                aria-label={item.label}
                aria-current="page"
                tabIndex={0}
                style={{ maxWidth: `${breadcrumbItemMaxWidth}px` }}
              >
                {item.label}
              </a>
              {shouldDisplayBadge && (
                <Badge count={badgeCount} content={badgeContent} icon={badgeIcon} badgeType={badgeType} />
              )}
            </>
          )}
        </>
      ) : (
        <>
          {isEllipsisActive ? (
            <Tooltip
              label={item.label}
              position="bottom"
              alignment="center"
              triggerStyles={{
                maxWidth: `${breadcrumbItemMaxWidth}px`,
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
              }}
              shouldFocusTrigger={false}
            >
              <Link
                href={item.link}
                label={item.label}
                subtle
                style={{ color: "var(--content-tertiary)", maxWidth: `${breadcrumbItemMaxWidth}px` }}
              />{" "}
              {shouldDisplayBadge && (
                <Badge count={badgeCount} content={badgeContent} icon={badgeIcon} badgeType={badgeType} />
              )}
            </Tooltip>
          ) : (
            <>
              <Link
                href={item.link}
                label={item.label}
                subtle
                style={{ color: "var(--content-tertiary)", maxWidth: `${breadcrumbItemMaxWidth}px` }}
              />
              {shouldDisplayBadge && (
                <Badge count={badgeCount} content={badgeContent} icon={badgeIcon} badgeType={badgeType} />
              )}
            </>
          )}
        </>
      )}
    </div>
  );
};

export default BreadcrumbItem;
