// packages/angular/projects/ds-rte-lib/src/lib/components/textarea/textarea.component.ts
import { CommonModule } from "@angular/common";
import { Component, input, computed, output, ElementRef, viewChild } from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import { REQUIREMENT_INDICATOR_VALUE } from "@rte-ds/core/components/required-indicator/required-indicator.constant";
import { TEXTAREA_ICON_SIZE } from "@rte-ds/core/components/textarea/textarea.constants";
import type {
  TextareaAssistiveTextAppearance,
  TextareaLabelPosition,
} from "@rte-ds/core/components/textarea/textarea.interface";

import { IconComponent } from "../icon/icon.component";
import { LinkComponent } from "../link/link.component";

@Component({
  selector: "rte-textarea",
  imports: [CommonModule, IconComponent, LinkComponent],
  standalone: true,
  templateUrl: "./textarea.component.html",
  styleUrl: "./textarea.component.scss",
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: TextareaComponent,
      multi: true,
    },
  ],
})
export class TextareaComponent {
  readonly id = input<string | undefined>(undefined);
  readonly name = input<string | undefined>(undefined);
  readonly ariaLabelledby = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly labelId = input<string | undefined>(undefined);
  readonly labelPosition = input<TextareaLabelPosition>("top");
  readonly assistiveTextLabel = input<string | undefined>(undefined);
  readonly assistiveTextAppearance = input<TextareaAssistiveTextAppearance>("description");
  readonly assistiveTextLink = input<string | undefined>(undefined);
  readonly required = input<boolean>(false);
  readonly showLabelRequirement = input<boolean>(false);
  readonly resizeable = input<boolean | string>(true);
  readonly maxLength = input<number | undefined>(undefined);
  readonly disabled = input<boolean>(false);
  readonly readOnly = input<boolean>(false);
  readonly value = input<string | undefined>(undefined);
  readonly rows = input<number>(3);
  readonly defaultValue = input<string | undefined>(undefined);
  readonly showCounter = input<boolean>(false);

  readonly assistiveTextIconSize = TEXTAREA_ICON_SIZE;

  readonly requirementIndicatorValue = computed(() =>
    this.required()
      ? this.showLabelRequirement()
        ? REQUIREMENT_INDICATOR_VALUE.required
        : REQUIREMENT_INDICATOR_VALUE.requiredIcon
      : REQUIREMENT_INDICATOR_VALUE.optional,
  );

  readonly change = output<Event>();
  readonly blur = output<FocusEvent>();

  readonly textareaRef = viewChild<ElementRef<HTMLTextAreaElement>>("textarea");

  readonly isAssistiveTextLinkVisible = computed(
    () => this.assistiveTextAppearance() === "link" && this.assistiveTextLink() !== undefined,
  );

  characterCount = 0;

  readonly isCounterVisible = computed(() => {
    return this.showCounter() && this.maxLength();
  });

  onInput(event: Event) {
    const target = event.target as HTMLTextAreaElement;
    this.characterCount = target.value.length;
    this.change.emit(event);
  }

  onBlur(event: FocusEvent) {
    this.textareaRef()?.nativeElement?.scrollTo({ top: 0 });
    this.blur.emit(event);
  }
}

// packages/react/src/components/textarea/Textarea.tsx
import type { TextareaProps as CoreTextareaProps } from "@rte-ds/core/components/textarea/textarea.interface";
import { ChangeEvent, FocusEvent, forwardRef, MutableRefObject, TextareaHTMLAttributes, useRef, useState } from "react";

import AssistiveText from "../assistivetext/AssistiveText";
import RequiredIndicator from "../requiredindicator/RequiredIndicator";
import { concatClassNames } from "../utils";

import style from "./Textarea.module.scss";

interface TextareaProps
  extends
    CoreTextareaProps,
    Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, "onChange" | "value" | "defaultValue" | "placeholder"> {
  onChange?: (event: ChangeEvent<HTMLTextAreaElement>) => void;
}

const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      className = "",
      id,
      name,
      required = false,
      onChange,
      onBlur,
      label,
      labelId,
      labelPosition = "top",
      assistiveTextLabel,
      assistiveTextAppearance = "description",
      ["aria-labelledby"]: ariaLabelledby,
      assistiveTextLink,
      showLabelRequirement = false,
      resizeable = "true",
      maxLength,
      defaultValue,
      showCounter,
      value,
      ...props
    },
    ref,
  ) => {
    const [characterCount, setCharacterCount] = useState(value?.length || defaultValue?.length || 0);

    const textareaRef: MutableRefObject<HTMLTextAreaElement | null> = useRef<HTMLTextAreaElement>(null);

    const displayCounter = showCounter && maxLength;

    const handleBlur = (event: FocusEvent<HTMLTextAreaElement, Element>) => {
      if (onBlur) {
        onBlur(event);
      }
      textareaRef.current?.scrollTo({ top: 0 });
    };

    const handleChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
      if (onChange) {
        onChange(event);
      }
      if (maxLength) {
        setCharacterCount(event.target.value.length);
      }
    };

    return (
      <div className={style.container} data-label-position={labelPosition}>
        {label && labelPosition === "side" && (
          <label id={labelId} className={style.label} htmlFor={id} data-label-position={labelPosition}>
            {label}
            <RequiredIndicator required={required} showLabelRequirement={showLabelRequirement} />
          </label>
        )}
        <div className={style["top-position-container"]} data-label-position={labelPosition}>
          <div className={style["header-container"]} data-label-position={labelPosition}>
            {label && labelPosition === "top" && (
              <label id={labelId} className={style.label} htmlFor={id} data-label-position={labelPosition}>
                {label}
                <RequiredIndicator required={required} showLabelRequirement={showLabelRequirement} />
              </label>
            )}
            {displayCounter && (
              <span className={style["character-counter"]}>
                {characterCount}/{maxLength}
              </span>
            )}
          </div>
          <div className={style["textarea-container"]} data-label-position={labelPosition}>
            <textarea
              ref={(node) => {
                textareaRef.current = node;
                if (typeof ref === "function") ref(node);
                else if (ref) ref.current = node;
              }}
              id={id}
              name={name}
              className={concatClassNames(style.textarea, className)}
              data-resizeable={resizeable}
              data-assistive-text-appearance={assistiveTextAppearance}
              onChange={handleChange}
              aria-labelledby={labelId || ariaLabelledby}
              maxLength={maxLength}
              onBlur={handleBlur}
              defaultValue={defaultValue}
              value={value}
              {...props}
            />
            {assistiveTextLabel && (
              <AssistiveText
                label={assistiveTextLabel}
                appearance={assistiveTextAppearance}
                showIcon={true}
                href={assistiveTextLink}
              />
            )}
          </div>
        </div>
      </div>
    );
  },
);

export default Textarea;
