// packages/react/src/components/sideNav/navMenu/NavMenu.tsx
import { NavItemProps } from "@rte-ds/core/components/side-nav/nav-item/nav-item.interface";
import { NavMenuProps as CoreNavMenuProps } from "@rte-ds/core/components/side-nav/nav-menu/nav-menu.interface";
import { dividerAppearanceBySideNavAppearance } from "@rte-ds/core/components/side-nav/side-nav.constants";
import { forwardRef, Fragment, HTMLAttributes, ReactNode, useState } from "react";

import Badge from "../../badge/Badge";
import Divider from "../../divider/Divider";
import Icon from "../../icon/Icon";
import NavItem from "../navItem/NavItem";
import NavContentWrapper from "../shared/NavContentWrapper";
import NavLabel from "../shared/NavLabel";
import NavTooltipWrapper from "../shared/NavTooltipWrapper";
import { getNavTabIndex } from "../shared/navUtils";
import useNavKeyboard from "../shared/useNavKeyboard";

import style from "./NavMenu.module.scss";

interface NavMenuProps extends CoreNavMenuProps, Omit<HTMLAttributes<HTMLLIElement>, "onClick"> {
  children?: ReactNode;
  isNested?: boolean;
  parentMenuOpen?: boolean;
}

const NavMenu = forwardRef<HTMLLIElement, NavMenuProps>(
  (
    {
      icon,
      showIcon = true,
      onClick,
      label,
      collapsed,
      link,
      items = [],
      open: controlledOpen,
      showMenuIcon = true,
      isNested,
      parentMenuOpen,
      appearance = "brand",
      badge,
      showDivider,
      ...props
    }: NavMenuProps,
    ref,
  ) => {
    const [internalOpen, setInternalOpen] = useState(false);
    const isOpen = controlledOpen !== undefined ? controlledOpen : internalOpen;
    const isControlled = controlledOpen !== undefined;

    function toggleMenu() {
      if (!isControlled) {
        setInternalOpen(!internalOpen);
      }
      if (onClick) {
        onClick();
      }
    }

    function handleEscape() {
      if (isOpen && !isControlled) {
        setInternalOpen(false);
      }
    }

    const { onKeyDown } = useNavKeyboard<HTMLElement>({
      onEnterOrSpace: toggleMenu,
      onEscape: handleEscape,
      includeArrowKeys: true,
      includeEscape: true,
    });

    const hasNestedItems = items.length;
    const shouldShowMenu = !collapsed && hasNestedItems;
    const nestedItemsParentMenuOpen = isOpen;
    const tabIndex = getNavTabIndex(parentMenuOpen);

    const chevronIcon =
      shouldShowMenu && showMenuIcon ? (
        <Icon name="arrow-chevron-right" className={style.menuIcon} data-open={isOpen} />
      ) : null;

    const menuContent = (
      <>
        <div className={style.menuContentLeft}>
          <NavLabel
            icon={icon}
            showIcon={showIcon}
            label={label}
            collapsed={collapsed}
            isNested={isNested}
            styleType="menu"
          />
        </div>
        <div className={style.menuContentRight}>
          {!collapsed && badge && (
            <Badge badgeType={badge.badgeType} size={badge.size} content={badge.content} count={badge.count} />
          )}
          {chevronIcon}
        </div>
      </>
    );

    const listItem = (
      <li
        className={style.navMenuContainer}
        data-collapsed={collapsed}
        data-appearance={appearance}
        data-nested={isNested}
        data-open={isOpen}
        ref={ref}
        {...props}
      >
        <NavContentWrapper
          link={link}
          label={label}
          tabIndex={tabIndex}
          onClick={toggleMenu}
          onKeyDown={onKeyDown}
          styleType="menu"
        >
          {menuContent}
        </NavContentWrapper>
        {shouldShowMenu && (
          <ul className={style.nestedMenu} data-open={isOpen}>
            {items.map((item: NavItemProps) => {
              const hasNestedItems = !!item.items?.length;
              if (hasNestedItems) {
                return (
                  <NavMenu
                    key={item.id || item.label}
                    label={item.label}
                    icon={item.icon}
                    showIcon={item.showIcon}
                    collapsed={collapsed}
                    link={item.link}
                    onClick={item.onClick}
                    items={item.items || []}
                    showMenuIcon={showMenuIcon}
                    showDivider={item.showDivider}
                    isNested={true}
                    parentMenuOpen={nestedItemsParentMenuOpen}
                    appearance={appearance}
                    badge={item.badge}
                  />
                );
              }
              return (
                <Fragment key={item.id || item.label}>
                  <li>
                    <NavItem
                      label={item.label}
                      icon={item.icon}
                      showIcon={item.showIcon}
                      collapsed={collapsed}
                      link={item.link}
                      onClick={item.onClick}
                      isNested={true}
                      parentMenuOpen={nestedItemsParentMenuOpen}
                      appearance={appearance}
                      badge={item.badge}
                    />
                  </li>
                  {item.showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
                </Fragment>
              );
            })}
          </ul>
        )}
      </li>
    );

    const wrappedListItem = (
      <NavTooltipWrapper label={label} collapsed={collapsed}>
        {listItem}
      </NavTooltipWrapper>
    );

    return (
      <>
        {wrappedListItem}
        {showDivider && <Divider appearance={dividerAppearanceBySideNavAppearance[appearance]} />}
      </>
    );
  },
);

export default NavMenu;

// packages/angular/projects/ds-rte-lib/src/lib/components/side-nav/nav-menu/nav-menu.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, input, output } from "@angular/core";
import { BadgeProps } from "@rte-ds/core/components/badge/badge.interface";
import { NavItemProps } from "@rte-ds/core/components/side-nav/nav-item/nav-item.interface";
import { getNavItemLabelIconSize } from "@rte-ds/core/components/side-nav/nav-item/nav-item.utils";
import { NavMenuProps } from "@rte-ds/core/components/side-nav/nav-menu/nav-menu.interface";
import { dividerAppearanceBySideNavAppearance } from "@rte-ds/core/components/side-nav/side-nav.constants";
import { SideNavAppearance } from "@rte-ds/core/components/side-nav/side-nav.interface";
import { ENTER_KEY, ESCAPE_KEY, SPACE_KEY } from "@rte-ds/core/constants/keyboard/keyboard.constants";

import { BadgeComponent } from "../../badge/badge.component";
import { DividerComponent } from "../../divider/divider.component";
import { IconComponent } from "../../icon/icon.component";
import { TooltipDirective } from "../../tooltip/tooltip.directive";
import { NavItemComponent } from "../nav-item/nav-item.component";

function getNavTabIndex(parentMenuOpen?: boolean): number {
  return parentMenuOpen === false ? -1 : 0;
}

export interface NavMenuOpenChangeEvent {
  id: string;
  open: boolean;
}

@Component({
  selector: "rte-nav-menu",
  imports: [CommonModule, IconComponent, BadgeComponent, DividerComponent, NavItemComponent, TooltipDirective],
  standalone: true,
  templateUrl: "./nav-menu.component.html",
  styleUrl: "./nav-menu.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavMenuComponent {
  readonly id = input<string | undefined>();
  readonly icon = input<string | undefined>();
  readonly showIcon = input<boolean>(true);
  readonly label = input.required<string>();
  readonly collapsed = input<boolean>(false);
  readonly link = input<string | undefined>();
  readonly items = input.required<NavItemProps[]>();
  readonly open = input<boolean | undefined>(false);
  readonly showMenuIcon = input<boolean>(true);
  readonly isNested = input<boolean>(false);
  readonly parentMenuOpen = input<boolean | undefined>();
  readonly appearance = input<SideNavAppearance>("brand");
  readonly badge = input<BadgeProps | undefined>();
  readonly showDivider = input<boolean>(false);

  readonly itemClick = output<string>();
  readonly openChange = output<NavMenuOpenChangeEvent>();

  constructor() {
    effect(
      () => {
        if (this.parentMenuOpen() === false && this.open()) {
          this.closeMenu();
        }
      },
      { allowSignalWrites: true },
    );
  }

  readonly hasNestedItems = computed<boolean>(() => !!this.items().length);
  readonly shouldShowMenu = computed<boolean>(() => !this.collapsed() && this.hasNestedItems());
  readonly tabIndex = computed<number>(() => getNavTabIndex(this.parentMenuOpen()));

  readonly dividerAppearance = computed(() => dividerAppearanceBySideNavAppearance[this.appearance()]);

  readonly iconSize = computed<number>(() => {
    return getNavItemLabelIconSize(this.isNested(), this.collapsed());
  });

  toggleMenu(): void {
    this.openChange.emit({ id: this.id() || this.label(), open: !this.open() });
  }

  handleEscape(): void {
    if (this.open()) {
      this.closeMenu();
    }
  }

  handleKeyDown(event: KeyboardEvent): void {
    if ([SPACE_KEY, ENTER_KEY].includes(event.key)) {
      event.preventDefault();
      this.toggleMenu();
    }
    if (event.key === ESCAPE_KEY) {
      event.preventDefault();
      this.handleEscape();
    }
  }

  hasNestedItemsForItem(item: NavItemProps): item is NavMenuProps {
    return !!item.items?.length;
  }

  handleMenuOpenChange(event: NavMenuOpenChangeEvent): void {
    const targetMenu = this.items().find((item) => item.id === event.id);
    if (targetMenu) {
      (targetMenu as NavMenuProps).open = event.open;
    }
  }

  handleMenuClick(itemId: string): void {
    const item = this.items().find((i) => i.id === itemId || i.label === itemId);
    if (item?.onClick) {
      item.onClick();
    }
  }

  private closeMenu(): void {
    this.openChange.emit({ id: this.id() || this.label(), open: false });
  }
}
